// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znhvcsdwmrvfceiswqlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuaHZjc2R3bXJ2ZmNlaXN3cWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTAzNTEsImV4cCI6MjA2MTE4NjM1MX0.zMKlbgxz4XSxv-tHHeCD9n4vufwiTWioIvbUjnq56fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);